### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by fabiocaccamo** [MattDiMu/gulp-sassvg#2]
Very nice mixin, this is exactly what I was looking for since 2 days.
Just some suggestions:
- In the documentation add an example that explain how to change the color (I had to read the sass function)
- Don't automatically set background-repeat, background-position and background-size if not passed as arguments.

**Comment by MattDiMu** [comment]
Thx, your feedback is appreciated.

You're right, the documentation in the README.md is currently suboptimal. In my defence, the .scss-file is documented in sassdoc-annotations. Therefore users using [sassdoc](https://github.com/SassDoc/sassdoc) in their project, would get a nice documention about all variables, functions and mixins available:

![sassdoc_tree](https://cloud.githubusercontent.com/assets/8099893/15534716/894b3e6e-226a-11e6-8e6f-714bd8c52e13.png)

### e.g. the documentation for the sassvg-list function
![sassdoc_sassvg-list](https://cloud.githubusercontent.com/assets/8099893/15534759/c8e12656-226a-11e6-8481-80e0f95a214b.png)


But as stated above, this is only for sassdoc-users and only after having already included the plugin. Will try to improve that.

Concerning the automatically set background-repeat, position and size. I found this a good idea, because
- background-repeat is (in 95% of the cases) always set to `no-repeat`, when used with an icon
- background-position is usually set to something different than `left top`as well.
- background-size should be set when using SVGs as background-images, as Internet Explorer sometimes behaves strangely otherwise

By the way, if you want to set the background-image only, you can use the similiar named `sassvg`-function:
```scss
background-image: sassvg("iconname", #FF00FF);
```

**Comment by MattDiMu** [comment]
Documentation has since improved and some screenshots added to the README.me
